connect-foundation/2019-12

client/.storybook/addons.ts, client/.storybook/config.ts, client/.storybook/webpack.config.js, client/package.json, client/src/setupTests.ts, client/tsconfig.json, yarn.lock
#55 스토리북 환경설정
#28 Enzyme, Jest
#5 Test Scripts
#26 문서화
- 디렉터리 구조와 샘플, client의 package.json 을 확인해주세요.
- [[테스트 전략](https://github.com/connect-foundation/2019-12/wiki/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%A0%84%EB%9E%B5), [컴포넌트 작성법](https://github.com/connect-foundation/2019-12/wiki/%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EC%9E%91%EC%84%B1%EB%B2%95)] 문서와 문서 내의 링크들을 확인해주세요.  E2E 테스트 관련 문서 작성은 한 페이지(템플릿) 완성 후에 테스트하며 작성할 예정입니다.
각 이슈에 상세한 내용이 있습니다.
=> [PR] Client 환경구성 및 문서화

server/src/models/Event.ts, server/src/models/Order.ts, server/src/models/OrderTicket.ts, server/src/models/TicketSubscription.ts, server/src/models/TicketType.ts, server/src/models/User.ts
#76
- BelongsTo 일 때 외래키 필드를 명시적으로 만듬
- HasMany 를 가지면 반대편에 외래키가 정의되어 있어야 함
- TicketType 에 price가 없어서 추가
=> [PR] 모델 변경

.gitignore, .travis.yml, server/.env, server/src/config/oauth_google.ts, server/src/config/server_url.ts, server/src/routes/api/auth/index.ts, server/src/services/passport.ts
#12 #17
Passport, passport-google-oauth 를 이용해서 google 로그인 환경 구성
-
model 이 만들어지면, token 발급과 User 검증을 통해 회원가입 페이지로 이동할지 결정할 예정
=> #12 [PR] Oauth API 제작

client/src/commons/constants/apis.ts, client/src/components/atoms/Btn/index.tsx, client/src/components/atoms/Divider/index.tsx, client/src/components/atoms/Icon/index.tsx, client/src/components/atoms/Input/index.tsx, client/src/components/atoms/Label/index.tsx, client/src/components/molecules/Card/index.tsx, client/src/components/molecules/FormInput/index.stories.tsx, client/src/components/molecules/FormInput/index.tsx, client/src/components/organisms/SignUpForm/index.stories.tsx, client/src/components/organisms/SignUpForm/index.tsx, client/src/pages/SignUp/index.tsx
#97
State의 관리 방법을 만들었고, 이에 따라 State 관리를하도록  작성함.
아토믹구조가 잘 보존 되어있는지, 이 구조를 적용했을 때 문제가 없을지 관심있게 봐주세요.
Test코드 어떻게 작성해야할까요?
=> [PR] State 관리방법을 적용한 회원가입 페이지를 만듦 / BaseComponent에 대한 모양을 변경함.

client/package.json, yarn.lock
- axios dependency 를 추가
- 비동기 API 요청을 위해 사용할 예정
#104 
Axios 모듈 추가
=> [PR] Axios 모듈 추가

yarn.lock
#120 
develop merge 후 한번 더 yarn.lock 을 정리했습니다
#122
=> [PR] regenerate yarn.lock

server/src/services/events.ts
=> [PR] fix events service wrong field name

package.json
#130 
pre-push test hook 제거입니다 👍
=> [PR] remove pre-push test hook

server/src/routes/api/events/controllers/getEvents.ts, server/src/routes/api/events/validators/getEvents.ts, server/src/services/events.ts, server/test/api/event.spec.ts
lastId 를 startAt 으로 날짜 비교로 변경
#134 
API 오류 수정
빠른 머지 부탁..!
테스트 포함함
=> [PR] fix get event api

server/src/routes/api/events/controllers/getEvent.ts, server/src/routes/api/events/controllers/index.ts, server/src/routes/api/events/index.ts, server/src/services/events.ts
#66
MERGE ASAP
나중에 테스트 및 리팩토링 예정
no Tested
=> [PR] 이벤트 디테일 API

client/src/App.tsx, yarn.lock
- fix detail page routing
- remove unnecessary variable
핫핫픽스
뜨거운 픽스,,, 
4명 페어코딩했습니다.
생략
=> [PR] fix: hottest fix

client/src/hooks/base/useFetch/index.spec.tsx, client/src/hooks/base/useFetch/index.ts
#150 
useFetch가 반복적으로 호출되던 현상을 useEffect를 사용하여 해결함
사용하지 않는 prop (isLoading)을 제거
Stable하지 않게 동작하던 현상을 해결 (반복적으로 호출하는 현상과 상태관리가 clear하지 않았던 점)
=> [PR] useFetch 개선

server/src/app.ts
#155 
서버가 켜져있으면 200을 reponse 해주는 라우터를 하나 만들어서 로드벨런서가 상태 체크를 할 수 있도록 함.
=> [PR] Health Check를 할 수 있는 라우터를 만듦

.travis.yml, reserve-server/src/routes/api/controllers/authUser.ts
=> [PR] Travis pre_deploy stage 추가

client/src/App.tsx, client/src/pages/NotFound/index.stories.tsx, client/src/pages/NotFound/index.tsx, client/src/pages/NotFound/template/index.tsx, client/src/pages/NotFound/template/style.ts
#180 404 NOT FOUND
단순 텍스트가 아닌 유명인사의 힘을 빌리기로 함
ask and go the blue
=> [PR] 404 NOT FOUND

client/src/commons/constants/routes.ts, client/src/components/organisms/CardGrid/index.tsx
#216 이벤트 주최하기 라우팅 버그
경로가 잘못 되어서 수정
없음
없음
=> [PR] 이벤트 주최하기 라우팅 버그 해결

client/src/components/organisms/Place/index.tsx, client/src/pages/EventDetail/store.tsx, client/src/pages/EventDetail/view.tsx, client/src/types/Data.ts
#193 
서버에서 보내주는 형태로 인터페이스를 수정함
=> [PR] flatten location in EventDetail interface

client/src/pages/EventDetail/template/index.tsx, client/src/pages/EventDetail/template/style.ts, client/src/pages/EventDetail/view.tsx
=> [PR] EventDetailPage(이벤트 상세) width 수정

client/src/components/organisms/SignUpForm/index.stories.tsx
#194
전역 변수에 knob이 설정되어 어떤 스토리에 방문해도 표시되는 것을 컴포넌트 내부로 이동하여 해결
=> [PR] 스토리북 실행 시 SignUp Knob이 바로 표시되는 현상 해결

README.md
없음.
인프라 구조 업데이트로 인한 리드미 수정
storybook deploy url 변경사항 추가 (https://storybook-bookus.netlify.com/)
사진이 현재 잘 작성되어 있는지.
=> [PR] README 에 레디스 관련 이미지 추가 / Docker hub 링크 추가

client/src/components/atoms/GoogleMap/index.tsx
#241 
- Storybook build를 위한 코드 작성
- Netlify에 환경변수 추가
- [Storybook build 환경변수는 STORYBOOK_ prefix 로 시작해야함](https://storybook.js.org/docs/configurations/env-vars/)
- 외부 라이브러리는 테스트를 작성하지 않음. 하지만 테스트를 작성해서 지도가 제대로 표시되는지 알 수 있으면 좋을 것 같은데 방법을 고민하는 중
- 로컬에서 배포하고 테스트 했으며, 실 배포URL에선 master branch를 바라보고 있으므로 이 변경사항이 merge되어 릴리즈되면 결과를 확인할 수 있음.
=> [PR] Live / Build 환경 Storybook에서 GoogleMap 이 표시되지 않는 현상 해결

client/src/components/atoms/GoogleMap/index.tsx
resolve #236 
구글맵이 이동되지 않고, 항상 해당 장소를 표시하도록 개선
=> [PR] 구글맵 draggable false

client/src/commons/constants/string.ts, client/src/components/organisms/SignUpForm/index.stories.tsx
=> [PR] SignUp 에서 패스워드 관련된 변수와 참조 제거

reserve-server/src/constants/index.ts, reserve-server/src/routes/api/controllers/authUser.ts, reserve-server/src/routes/api/controllers/checkTicket.ts, reserve-server/src/routes/api/controllers/orderTicket.ts, reserve-server/src/services/transactions.ts, reserve-server/test/api.spec.ts
#250 
티켓 구매 날짜가 아닐경우 
```js
{
state: 0,
message: "wrong date"
}
```
티켓이 다 팔렸을 경우
```js
{
state: 1,
message: "ticket sold out"
}
```
티켓을 구매한도를 초과해서 구매하려고 시도한 경우
```js
{
state: 2,
message: "limit exceed ticket per person"
}
```
티켓 구매 완료
```js
{
message: "success"
}
```
유저 인증 안됨
```js
{
message: "unauthorized"
}
```
티켓 이 존재하지 않을 경우
```js
{
message: "wrong number of ticket"
}
```
원하는 인자가 없음
이제 위와 같은 형식으로 body를 리턴해줌.
테스트 작성 후 다 통과했었는데 로직부분 잘 되어있는지 리턴 잘 되는지 봐주시면 좋을 것 같습니다.
성동님이 프론트쪽 약간 수정 부탁드려용..
reserve-server에 constants를 만들었습니다 이부분이 괜찮은지, 어떤식으로 바뀌면 좋을지 알려주세요
=> [PR] 티켓 구매시 오류 메세지를 정형화함.

client/src/apis/auth.ts, client/src/apis/event.ts, client/src/apis/index.ts, client/src/apis/user.ts, client/src/libs/axios.ts, client/src/pages/EventJoin/view.tsx, client/src/pages/Main/index.tsx, client/src/pages/SignUp/store.tsx, client/src/stores/accountStore.tsx
#196 
Client에서 비동기 API 사용을 개선했습니다.
`apis/` 하위의 파일들, 실제 사용 예 `import API from 'apis'`
디렉터리는 `apis/`, `libs/axios` 두가지로 구성해보았습니다. 개선 방향이 있다면 코멘트 부탁드려요.  
axios.create 옵션에 더 추가할 사항이 있다면 말씀해주세요!
=> [PR] Client의 비동기 API 사용 개선

.travis.yml, server/test/api/event.spec.ts, server/tsconfig.json
#262 
- 이전에 설정하였던 typeRoots 제거
- 트라비스에서 describe, it 등 타입을 못찾던 warning 문제 해결
=> [PR] 트라비스에서 describe, it 등 타입을 못찾던 warning 문제 해결

package.json, reserve-server/package.json, reserve-server/tsconfig.json, server/package.json, server/tsconfig.json
=> [PR] tsconfig typeRoots 수정

reserve-server/tsconfig.json, server/tsconfig.json
#288 
빌드는 되는데, 실행이 안되던 문제가 있었습니다
=> [PR] 서버 ts-node 실행 문제 fix

reserve-server/src/routes/api/controllers/authUser.ts, server/package.json, server/src/routes/middlewares/index.ts, server/src/routes/middlewares/isLogin.ts, server/test/middleware/isLogin.spec.ts, yarn.lock
#251 
로그인 여부를 확인하는 미들웨어를 만듦
만약 로그인이 안되어있으면, 401을 리턴해주는 함수임.=
첫 미들웨어 테스트니까 많이 봐주세요
.env 극혐
=> [PR] 로그인 확인용 미들웨어 추가

server/src/routes/api/users/controllers/getUserTickets.ts, server/src/routes/api/users/controllers/index.ts, server/src/routes/api/users/index.ts, server/src/routes/api/users/validators/createUser.ts, server/src/routes/middlewares/isLogin.ts, server/src/services/index.ts, server/src/services/userTickets.ts, server/src/types/express/index.d.ts, server/test/api/__snapshots__/user.spec.ts.snap, server/test/api/user.spec.ts
#270
테스트 작성중. 조금만 기달려주세요.
로그인이 안되어있으면 401 을 리턴함.
아래와 같은 사항을 로그인 된 유저에게 리턴함.
```ts
[
{
"id": number,
"userId": number,
"title": string,
"startAt": date,
"endAt": date,
"place": string,
"address": string,
"placeDesc": string,
"mainImg": string,
"ticket": {
"id": number,
"eventId": number,
"name": string,
"desc": string,
"price": number,
"quantity": number,
"leftCnt": number,
"isPublicLeftCnt": boolean,
"maxCntPerPerson": number,
"salesStartAt": date,
"salesEndAt": date,
"refundEndAt": date
},
"userTickets": [
{
"id": number,
"ticketTypeId": number,
"userId": number,
"isAttendance": boolean,
"createdAt": date
},
...
]
}
...
]
```
로직이 맘에 드십니까 여러분
=> [PR] GET /api/users/tickets 마이페이지 내 티켓 확인용 API

client/src/pages/EventJoin/index.tsx, client/src/pages/EventJoin/style.ts
#311 remove unused import and files
build error
없음
없음
=> [PR] remove unused import and files

client/src/components/atoms/Img/index.stories.tsx
#263 
Img Atom의 스타일을 모두 inherit해서 스타일링을 랩핑을 유도하여 만들었기 때문에 스토리북에서 수정
없음
없음
=> [PR] Img Atom 스토리북 수정

client/src/components/organisms/SignUpForm/index.stories.tsx
#269
SignUp story에 작성된 global knob이 전체 스토리에 영향을 끼쳐 이를 수정함
.
여러분 전역에는 Knob을 사용하지 않기로 해요!
=> [PR] Storybook global knob in SignUp story 제거 

README.md
#328
<!— 변경한 내용과 그 이유를 적어주세요. —>
=> [PR] 리드미 이미지 업데이트

server/src/routes/api/users/controllers/deleteUserTicket.ts, server/src/services/userTickets.ts, server/src/utils/redis.ts, server/test/api/event.spec.ts, server/test/api/user.spec.ts
#326 
현재 티켓 삭제시에 남은 티켓수가 안 줄어들고, Redis 의 블록이 풀리지 않았음. 이를 해결함.
로직 봐주시고 테스트 코드에서 다시 Rollback 할 수 있도록 했는데 이게 괜찮을지 봐주세요.
없습니다.
=> [PR] 티켓 삭제시에 트렌젝션을 통해 leftCnt 를 늘리고, redis Block 을 풀어줌.

client/src/components/organisms/Place/index.stories.tsx, client/src/components/organisms/Place/index.tsx, client/src/hooks/base/useApiRequest/index.ts, client/src/pages/EventDetail/index.tsx, client/src/pages/EventJoin/index.tsx, client/src/types/Data.ts
#336 
- 이벤트 참여 페이지에서 이벤트 글로벌 스토어가 도입되기 전에 작성되고 이후 도입 후에 다시 수정하는 걸 깜빡했습니다! 스토어를 이용하는 코드로 수정했습니다. 🙋‍♂️
- 불필요한 Location interface 제거
=> [PR] 이벤트 참여 페이지에서 이벤트 내용이 정상적으로 보여지지 않는 현상 해결

client/src/apis/auth.ts, client/src/apis/event.ts, client/src/apis/user.ts, client/src/components/molecules/LNB/index.tsx, client/src/components/molecules/StepList/index.tsx, client/src/components/organisms/CardGrid/index.stories.tsx, client/src/components/organisms/TicketBox/index.tsx, client/src/hooks/base/useApiRequest/index.ts, client/src/hooks/meta/accountReducer/index.ts, client/src/pages/EventJoin/index.tsx, client/src/pages/MyPage/index.tsx, client/src/pages/MyPage/reducer.ts, client/src/pages/SignUp/store.tsx, client/src/stores/accountStore.tsx, client/src/stores/eventsStore.tsx
#360 
리뷰어님 리뷰에 따른 리팩토링을 진행을 진행했습니다. 각 코멘트에 대한 변경사항으로 보시면 됩니다. 자세한 내용은 위에 있는 PR에 있습니다!
- Object literal 적극 사용
- 함수 분리
. 
.
=> [PR] W6 리뷰에 따른 리팩토링

client/package.json
#389 
월 500번까지 무료고 이후에는 유료플랜을 구매해야되네요.. ㅠㅠ
데모를 위한 녹화는 로컬에서 직접 하도록 하겠습니다!
=> [PR] Disable Cypress video recording

client/src/App.tsx
#418 
상태를 추가하여 Loading 후에 결과를 평가하여 라우팅을 반환합니다.
**이제 권한 체크 후 라우팅 잘됩니다.**
자세한 내용은 이슈를 참고
.
.
=> [PR] Private Router 개선

client/src/hooks/useApiRequest.ts
=> [PR] useApiRequest 성공 / 에러 핸들링 개선

client/src/hooks/useApiRequest.ts, client/src/stores/accountStore/index.tsx
#432 
error 객체가 AxiosError 가 아닐 경우에 대비하여 response status를 안넣고 갈 수 있도록 해놓음.
관련 사항을 사용중인 것들에 대해서 모두 수정이 필요함.
=> [PR] useAPIRequest 에서 일어날 수 있는 버그를 없앰

server/src/routes/api/users/controllers/deleteUserTicket.ts, server/src/services/userTickets/deleteUserTicketById.ts, server/test/api/user.spec.ts
=> [PR] 티켓 환불을 환불 날짜 안에 있어야만 환불이 가능하도록 함. 날짜가 지났을 경우 에러코드 400

client/src/components/molecules/LNB/index.tsx, client/src/hooks/useApiRequest.ts, client/src/pages/MyPage/helper.tsx, client/src/pages/MyPage/template/BoughtTicketEvent/style.ts, client/src/pages/MyPage/view.tsx, client/src/utils/getImageURL/imageTypes.ts
=> [1차 / PR] 셀프-버그데이 / 티켓 구매, 상세, 마이페이지 트러블슈팅

server/src/routes/api/events/validators/createEvent.ts
=> [PR] 이벤트 만들기 검증 버그 수정

server/src/routes/api/events/validators/createEvent.ts
#427 
이벤트 만들기 API 검증에서 설명을 optional 로 하기
=> [PR] 이벤트 만들기 API 검증에서 설명을 optional 로 하기

client/src/commons/constants/string.ts, client/src/components/atoms/ImgSelector/index.stories.tsx, client/src/components/atoms/ImgSelector/index.tsx
#444 
Img Selector 에서 File Size Limit 기능 추가
=> [PR] Img Selector 에서 File Size Limit 기능 추가

client/src/components/organisms/EventHeader/index.tsx, client/src/components/organisms/Ticket/index.tsx, client/src/components/organisms/Ticket/style.ts, client/src/components/organisms/TicketBox/index.tsx, client/src/pages/EventDetail/index.tsx, client/src/pages/EventJoin/index.tsx
=> [PR / 3차] 티켓 구매, 상세, 마이페이지 트러블슈팅

client/src/App.tsx, client/src/pages/Login/index.tsx, client/src/stores/afterLoginStore/index.tsx
#348 #449 
필요에 의해서 만듦.
여기서 Public Router를 어쩔수 없이 만들어서 추가시킴. 별다른 이유 없이, 내일 시나리오를 알려드릴 예정. 궁금하면 물어봇에ㅛ
=> [PR] 로그인 이후 로그인 이전에 접속하려던 페이지에 접속시켜줌.

reserve-server/src/common/constants/index.ts, reserve-server/src/routes/api/controllers/orderTicket.ts
레저브 서버가 에러를 실어 보내는 것을 삭제함.
#347 
서버가 에러코드를 반환하는 것을 막음
=> [PR] 티켓 예매시 err가 body로 실어보내지는 것을 방지함.

server/src/services/events/getEventById.ts, server/src/services/events/getEvents.ts
is ticket public cnt 가 false 일 경우 leftCnt 를 -1로 변경해줌
getEvent와 getEvents 두 부분에 대해서 동일한 사항을 적용함.
=> [PR] 티켓 남은 개수가 안보여야 할 경우, 티켓의 leftCnt 를 -1 로 변경해서 보내줌.

client/.eslintrc.json, client/src/components/molecules/IconBtn/index.tsx, client/src/components/organisms/Ticket/style.ts, client/src/hooks/useFetch.spec.tsx
#463 
- travis 에서 build fail 방지
- travis 빌드 fail 해결
사용안한 변수 등이 있으면 커밋 안됩니당
=> [PR] travis 빌드 fail 해결 및 재발 방지

client/src/pages/EventCreate/store.tsx, server/src/routes/api/events/validators/createEvent.ts
#459 티켓 가격 0원 허용
#457 Client 와 Server 의 이벤트 만들기 페이지에서의 Validation이 맞지 않음.
티켓 가격이 0원이어도 허용되어야 합니다!
ㅇ_ㅇ
=> [PR] 티켓 가격 0원 허용

client/src/pages/Login/index.tsx
#468 
로그인 페이지에서 콘솔로그를 지우고, 불필요한 변수를 삭제함.
=> [PR] 로그인페이지에서 console.log() 삭제.

server/src/services/events/getEventById.ts, server/src/services/events/getEvents.ts
#473 
- 비공개이더라도 매진이면 left count를 0으로 보냅니다.
=> [PR] 비공개이더라도 매진이면 left count를 0으로 보내기

client/src/App.tsx, client/src/apis/event.ts, client/src/apis/index.ts, reserve-server/src/routes/api/controllers/checkTicket.ts, reserve-server/src/routes/api/index.ts
=> [PR] event join 을 체크하는 react router 생성, reserve server에서 관련 로직을 체킹

client/src/pages/MyPage/store.tsx, client/src/pages/MyPage/view.tsx
=> [PR] MyPage context를 state, action 으로 분리

client/src/commons/constants/number.ts, client/src/commons/constants/string.ts, client/src/components/molecules/DateTimePicker/index.tsx, client/src/pages/EventCreate/store.tsx, client/src/pages/EventCreate/view.tsx, client/src/stores/eventsStore/index.tsx, client/src/stores/eventsStore/reducer.ts, client/src/utils/validateInput/index.ts
#484 이벤트 예약 Alert 문구 수정 
#485 이벤트 만들기 폼 시간 버그
버그 수정입니당당
없음
없음
=> [PR] 이벤트 만들기 폼 시간 버그

client/src/components/organisms/EventHeader/index.tsx
#477 
버튼이 티켓 오픈 전에 시간에 맞게 OO 후 오픈을 표시하도록 하고,
시간이 되면 등록 버튼이 표시되도록 함
아래 내용이 적절할까요
- 60초 이하 남았을 때, 300ms 마다 반복
- 60분 이하 남았을 때, 10초 마다 반복
- 24시간 이하 남았을 때, 10분 마다 반복
- 그 외 1시간 마다 반복
=> [PR] 티켓 구입 타이머 버튼

client/src/components/organisms/TicketBox/index.tsx, client/src/pages/Main/index.tsx, client/src/pages/MyPage/helper.tsx
#323 
Frontend 에서 non-null-assertion 제거 !!!!
없음 
없음
=> [PR] Frontend 에서 non-null-assertion 제거 

client/package.json, yarn.lock
#504
Cypress version up (3.6.3 => 3.8.0)
.
.
=> [PR] Cypress 버전 업데이트 (3.6.3 => 3.8.0)

client/src/commons/constants/string.ts, client/src/components/molecules/DateTimePicker/index.tsx
이슈없이 PR날렸습니당.
이벤트 만들 때, 날짜 입력을 키보드로 입력가능하게 함
이전에는 에러가 떴습니다ㅠ
없음
없음
=> [PR] 이벤트 만들 때, 날짜 입력을 키보드로 입력가능하게 함

client/src/components/atoms/TuiEditor/index.tsx
=> [PR] TUI editor 이미지 버튼 제거

client/src/components/molecules/DropDown/index.tsx, client/src/components/molecules/SearchMap/index.tsx, client/src/components/organisms/EventSection/style.ts
이슈가 없습니다.
<!— 변경한 내용과 그 이유를 적어주세요. —>
=> [PR] hotfix 에서 수정된 사항을 develop 브랜치에 적용
